name: "Security"

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
  schedule:
    - cron: "0 0 * * 0"

permissions: { }

jobs:
  codeql:
    name: "CodeQL"
    runs-on: "ubuntu-latest"

    permissions:
      security-events: write

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"
        with:
          persist-credentials: false
      - name: "Initialize CodeQL"
        uses: "github/codeql-action/init@v3"
        with:
          languages: "go"
      - name: "Autobuild"
        uses: "github/codeql-action/autobuild@v3"
      - name: "Perform CodeQL Analysis"
        uses: "github/codeql-action/analyze@v3"
