name: "Trivy"

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
  schedule:
    - cron: "0 0 * * 0"

permissions: { }

jobs:
  trivy:
    name: "Trivy"
    runs-on: "ubuntu-latest"

    permissions:
      security-events: write

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"
        with:
          persist-credentials: false

      - name: "Run Trivy vulnerability scanner in repo mode"
        uses: "aquasecurity/trivy-action@master"
        with:
          scan-type: "fs"
          ignore-unfixed: true
          format: "sarif"
          output: "trivy-results.sarif"
          severity: "CRITICAL,HIGH"

      - name: "Upload Trivy scan results to GitHub Security tab"
        uses: "github/codeql-action/upload-sarif@v3"
        with:
          sarif_file: "trivy-results.sarif"